org: duyduc1110
app: duyduc1110
service: aws-python-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-offline
